#!/bin/bash

sudo apt-add-repository -y universe && sudo apt -y update

xargs sudo apt -y install < packagefile

chsh -s $(which zsh)

sudo cat ./env > /etc/environment

mkdir ~/Projetos ~/.local/bin

make all
